apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "tailscale.fullname" . }}
  labels:
    {{- include "tailscale.labels" . | nindent 4 }}
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["secrets"]
    # Create can not be restricted to a resource name.
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "update", "patch"]
    resourceNames:
      {{- range $i := until (int .Values.replicas) }}
      - {{ include "tailscale.fullname" $ }}-{{ $i }}
      {{- end }}
